server:
  port: 48080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labeling?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        jdbc:
          lob:
          non_contextual_creation: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
